name: Python CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
    branches:
      - "**"

jobs:
  run_tests:
    name: tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -r requirements_dev.txt

      - name: Install PyTorch (CPU)
        run: pip install . -f https://download.pytorch.org/whl/torch_stable.html

      - name: Run Tests
        run: make test
